#!/bin/bash
#$ -N casanovo_non_autoregressive_check
#$ -cwd
#$ -o casanovo_sequence_nonAR.out
#$ -e casanovo_sequence_nonAR.err
#$ -l mfree=120G,cuda=1,gpgpu=TRUE
#$ -V

source /net/noble/vol1/home/ddesai22/anaconda3/etc/profile.d/conda.sh
conda activate casanovo_5

echo "Conda environment:"
which python
which casanovo

casanovo sequence  -m  /net/noble/vol1/home/ddesai22/best.ckpt /net/noble/vol1/home/ddesai22/projects/casanovo/sample_data/sample_preprocessed_spectra.mgf /net/noble/vol1/home/ddesai22/projects/casanovo/sample_data/sample_preprocessed_spectra.mgf

